baseurl = "https://chess-islands.netlify.app"
DefaultContentLanguage = "en"
title = "Chess Islands"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "3D Social Chess Platform"
  mainSections = ["post","posts"]
  logo = "img/chess-islands-icon.png" # Expecting square dimensions
  favicon = "img/chess-islands-icon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[[Params.bigimg]]
 src = "img/thumbnail-dark.png"
 desc = "Thumbnail for Chess Islands"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
 # position: see values of CSS background-position.
#  position = "center top"
# [[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Alan Chen"
  email = "alanyngchen@gmail.com"
  twitter = "https://x.com/ChessIslands"
  discord = "https://discord.gg/8gBPrAEpjq"
  bluesky = "chessislands.bsky.social"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3